server.port=${SERVER_PORT:8080}
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true

# Production Service URLs
spring.cloud.gateway.routes[0].uri=${USER_SERVICE_URL:lb://user-service}
spring.cloud.gateway.routes[1].uri=${RESTAURANT_SERVICE_URL:lb://restaurant-service}
spring.cloud.gateway.routes[2].uri=${ORDER_CART_SERVICE_URL:lb://order-cart-service}
spring.cloud.gateway.routes[3].uri=${PAYMENT_SERVICE_URL:lb://payment-service}

